/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Gestor;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author guide
 */
public class InterfazMusica extends javax.swing.JFrame {
     // Referencia a FormularioPrincipal para mostrar ruta
     public InterfazPrincipal interfazPrincipal;
    
    /**
     * Creates new form InterfazMusica
     */
    public InterfazMusica() {
        initComponents();
        this.setLocationRelativeTo(null);//centrar Jpanel
    }

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Busqueda = new com.Gestor.PanelRound();
        Ruta = new com.Gestor.PanelRound();
        MostrarRuta = new javax.swing.JTextField();
        Filtro = new javax.swing.JComboBox<>();
        CambiarRuta = new com.Gestor.PanelRound();
        Filtrar1 = new com.Gestor.PanelRound();
        ListadoMusica = new com.Gestor.PanelRound();
        BotonRegreso = new javax.swing.JButton();
        Propiedades = new com.Gestor.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Busqueda.setBackground(new java.awt.Color(204, 204, 204));
        Busqueda.setRoundBottomLeft(25);
        Busqueda.setRoundBottomRight(25);
        Busqueda.setRoundTopLeft(25);
        Busqueda.setRoundTopRight(25);
        Busqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ruta.setBackground(new java.awt.Color(102, 102, 102));
        Ruta.setRoundBottomLeft(25);
        Ruta.setRoundBottomRight(25);
        Ruta.setRoundTopLeft(25);
        Ruta.setRoundTopRight(25);
        Ruta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RutaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RutaLayout = new javax.swing.GroupLayout(Ruta);
        Ruta.setLayout(RutaLayout);
        RutaLayout.setHorizontalGroup(
            RutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        RutaLayout.setVerticalGroup(
            RutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Busqueda.add(Ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        MostrarRuta.setEditable(false);
        MostrarRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarRutaActionPerformed(evt);
            }
        });
        Busqueda.add(MostrarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 460, -1));

        Filtro.setBackground(new java.awt.Color(102, 102, 102));
        Filtro.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltroActionPerformed(evt);
            }
        });
        Busqueda.add(Filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 70, 20));

        CambiarRuta.setBackground(new java.awt.Color(102, 102, 102));
        CambiarRuta.setRoundBottomLeft(25);
        CambiarRuta.setRoundBottomRight(25);
        CambiarRuta.setRoundTopLeft(25);
        CambiarRuta.setRoundTopRight(25);
        CambiarRuta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Filtrar1.setBackground(new java.awt.Color(102, 102, 102));
        Filtrar1.setRoundBottomLeft(25);
        Filtrar1.setRoundBottomRight(25);
        Filtrar1.setRoundTopLeft(25);
        Filtrar1.setRoundTopRight(25);
        Filtrar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CambiarRuta.add(Filtrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 70, 20));

        Busqueda.add(CambiarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 70, 20));

        jPanel1.add(Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 750, 40));

        ListadoMusica.setBackground(new java.awt.Color(204, 204, 204));
        ListadoMusica.setRoundBottomLeft(25);
        ListadoMusica.setRoundBottomRight(25);
        ListadoMusica.setRoundTopLeft(25);
        ListadoMusica.setRoundTopRight(25);
        ListadoMusica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonRegreso.setBackground(new java.awt.Color(102, 102, 102));
        BotonRegreso.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        BotonRegreso.setForeground(new java.awt.Color(255, 255, 255));
        BotonRegreso.setText("Inicio");
        BotonRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresoActionPerformed(evt);
            }
        });
        ListadoMusica.add(BotonRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jPanel1.add(ListadoMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, 390));

        Propiedades.setBackground(new java.awt.Color(204, 204, 204));
        Propiedades.setRoundBottomLeft(25);
        Propiedades.setRoundBottomRight(25);
        Propiedades.setRoundTopLeft(25);
        Propiedades.setRoundTopRight(25);
        Propiedades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Propiedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 270, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void FiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FiltroActionPerformed

    private void MostrarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarRutaActionPerformed
      /*  String rutaCarpeta = interfazPrincipal.getRutaCarpeta();
        if (rutaCarpeta != null && !rutaCarpeta.isEmpty()) {//si la ruta esta llena
            MostrarRuta.setText(rutaCarpeta); // Mostrar la ruta en el campo de texto
        } else {
            MostrarRuta.setText( "No se ha seleccionado ninguna carpeta.");//si no hay ruta
        }*/
    
    }//GEN-LAST:event_MostrarRutaActionPerformed
    
    private void BotonRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresoActionPerformed
        this.setVisible(false);
        interfazPrincipal.setVisible(true);
    }//GEN-LAST:event_BotonRegresoActionPerformed

    private void RutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RutaMouseClicked
        
    }//GEN-LAST:event_RutaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegreso;
    private com.Gestor.PanelRound Busqueda;
    private com.Gestor.PanelRound CambiarRuta;
    private com.Gestor.PanelRound Filtrar1;
    private javax.swing.JComboBox<String> Filtro;
    private com.Gestor.PanelRound ListadoMusica;
    private javax.swing.JTextField MostrarRuta;
    private com.Gestor.PanelRound Propiedades;
    private com.Gestor.PanelRound Ruta;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
