/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Gestor;

import java.awt.Color;
import java.io.File;//para archivoso
import java.util.HashMap; //para los duplicados
import java.util.List;//para que funcione la funcion de busqueda
import java.util.Map; //para los duplicados
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author guide
 */
public class InterfazPrincipal extends javax.swing.JFrame {
    //public InterfazPrincipal interfazPrincipal;    
      public InterfazMusica interfazMusica;
      public InterfazVideo interfazVideo;
      public InterfazFlv interfazFlv;
      public InterfazImagen interfazImagen;
    
    /**
     * Creates new form InterfazPrincipal
     */

    public InterfazPrincipal() {//constructor
        initComponents();
         this.setLocationRelativeTo(null);//centrar Jpanel   
         interfazMusica = new InterfazMusica();
         interfazVideo = new InterfazVideo();
         interfazImagen = new InterfazImagen();
         interfazFlv = new InterfazFlv();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonMusica1 = new javax.swing.JButton();
        fondo = new javax.swing.JPanel();
        nodo1 = new com.Gestor.PanelRound();
        BotonMusica = new javax.swing.JButton();
        BotonVideo = new javax.swing.JButton();
        BotonFlv = new javax.swing.JButton();
        BotonImagen = new javax.swing.JButton();
        Buscar = new com.Gestor.PanelRound();
        Filtrar = new com.Gestor.PanelRound();
        Datos = new com.Gestor.PanelRound();
        Pestaniaspanle = new javax.swing.JTabbedPane();
        panelMusica = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelVideo = new javax.swing.JPanel();
        panelVideo1 = new javax.swing.JPanel();
        panelFlv = new javax.swing.JPanel();
        panelImagen = new javax.swing.JPanel();
        panelDuplicados = new javax.swing.JPanel();
        RutaSeleccionada = new javax.swing.JTextField();
        NodoPrincipal = new com.Gestor.PanelRound();
        NombreGestor = new com.Gestor.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        GraficasAlmacenamiento = new com.Gestor.PanelRound();
        TotalDeArchivos = new javax.swing.JLabel();
        NumeroArchivos = new javax.swing.JTextField();
        EspacioOcupado = new javax.swing.JTextField();
        EspacioOcupadoLabel = new javax.swing.JLabel();
        TotalDeDuplicados = new javax.swing.JLabel();
        EspacioDuplicados = new javax.swing.JTextField();
        Duplicados = new javax.swing.JButton();
        MusicaLabel = new javax.swing.JLabel();
        VideosLabel = new javax.swing.JLabel();
        ImagenesLabel = new javax.swing.JLabel();
        ChooseFile = new com.Gestor.PanelRound();
        Origen9 = new javax.swing.JLabel();

        BotonMusica1.setBackground(new java.awt.Color(51, 51, 51));
        BotonMusica1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/music128x128.png"))); // NOI18N
        BotonMusica1.setBorder(null);
        BotonMusica1.setBorderPainted(false);
        BotonMusica1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMusica1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMusica1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMusica1MouseExited(evt);
            }
        });
        BotonMusica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMusica1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(0, 0, 0));
        fondo.setMinimumSize(new java.awt.Dimension(800, 500));
        fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nodo1.setBackground(new java.awt.Color(153, 153, 153));
        nodo1.setForeground(new java.awt.Color(153, 153, 153));
        nodo1.setRoundBottomLeft(25);
        nodo1.setRoundBottomRight(25);
        nodo1.setRoundTopLeft(25);
        nodo1.setRoundTopRight(25);
        nodo1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonMusica.setBackground(new java.awt.Color(51, 51, 51));
        BotonMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/music1.png"))); // NOI18N
        BotonMusica.setBorder(null);
        BotonMusica.setBorderPainted(false);
        BotonMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMusicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMusicaMouseExited(evt);
            }
        });
        BotonMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMusicaActionPerformed(evt);
            }
        });
        nodo1.add(BotonMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 44, 74, -1));

        BotonVideo.setBackground(new java.awt.Color(51, 51, 51));
        BotonVideo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Video64x64.png"))); // NOI18N
        BotonVideo.setBorder(null);
        BotonVideo.setBorderPainted(false);
        BotonVideo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVideoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVideoMouseExited(evt);
            }
        });
        BotonVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVideoActionPerformed(evt);
            }
        });
        nodo1.add(BotonVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 44, 74, -1));

        BotonFlv.setBackground(new java.awt.Color(51, 51, 51));
        BotonFlv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/FLV64x64.png"))); // NOI18N
        BotonFlv.setBorder(null);
        BotonFlv.setBorderPainted(false);
        BotonFlv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonFlv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonFlvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonFlvMouseExited(evt);
            }
        });
        BotonFlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFlvActionPerformed(evt);
            }
        });
        nodo1.add(BotonFlv, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 44, 74, -1));

        BotonImagen.setBackground(new java.awt.Color(51, 51, 51));
        BotonImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Imagen64x64.png"))); // NOI18N
        BotonImagen.setBorder(null);
        BotonImagen.setBorderPainted(false);
        BotonImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonImagenMouseExited(evt);
            }
        });
        BotonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonImagenActionPerformed(evt);
            }
        });
        nodo1.add(BotonImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 44, 70, -1));

        Buscar.setRoundBottomLeft(25);
        Buscar.setRoundBottomRight(25);
        Buscar.setRoundTopLeft(25);
        Buscar.setRoundTopRight(25);

        javax.swing.GroupLayout BuscarLayout = new javax.swing.GroupLayout(Buscar);
        Buscar.setLayout(BuscarLayout);
        BuscarLayout.setHorizontalGroup(
            BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );
        BuscarLayout.setVerticalGroup(
            BuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        nodo1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 26));

        Filtrar.setRoundBottomLeft(25);
        Filtrar.setRoundBottomRight(25);
        Filtrar.setRoundTopLeft(25);
        Filtrar.setRoundTopRight(25);

        javax.swing.GroupLayout FiltrarLayout = new javax.swing.GroupLayout(Filtrar);
        Filtrar.setLayout(FiltrarLayout);
        FiltrarLayout.setHorizontalGroup(
            FiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        FiltrarLayout.setVerticalGroup(
            FiltrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        nodo1.add(Filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 6, -1, -1));

        Datos.setRoundBottomLeft(25);
        Datos.setRoundBottomRight(25);
        Datos.setRoundTopLeft(25);
        Datos.setRoundTopRight(25);

        panelMusica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelMusica.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 250));

        Pestaniaspanle.addTab("tab1", panelMusica);

        javax.swing.GroupLayout panelVideo1Layout = new javax.swing.GroupLayout(panelVideo1);
        panelVideo1.setLayout(panelVideo1Layout);
        panelVideo1Layout.setHorizontalGroup(
            panelVideo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        panelVideo1Layout.setVerticalGroup(
            panelVideo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelVideoLayout = new javax.swing.GroupLayout(panelVideo);
        panelVideo.setLayout(panelVideoLayout);
        panelVideoLayout.setHorizontalGroup(
            panelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVideoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelVideo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelVideoLayout.setVerticalGroup(
            panelVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVideoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelVideo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Pestaniaspanle.addTab("tab2", panelVideo);

        javax.swing.GroupLayout panelFlvLayout = new javax.swing.GroupLayout(panelFlv);
        panelFlv.setLayout(panelFlvLayout);
        panelFlvLayout.setHorizontalGroup(
            panelFlvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        panelFlvLayout.setVerticalGroup(
            panelFlvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        Pestaniaspanle.addTab("tab3", panelFlv);

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        Pestaniaspanle.addTab("tab4", panelImagen);

        javax.swing.GroupLayout panelDuplicadosLayout = new javax.swing.GroupLayout(panelDuplicados);
        panelDuplicados.setLayout(panelDuplicadosLayout);
        panelDuplicadosLayout.setHorizontalGroup(
            panelDuplicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        panelDuplicadosLayout.setVerticalGroup(
            panelDuplicadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        Pestaniaspanle.addTab("tab5", panelDuplicados);

        javax.swing.GroupLayout DatosLayout = new javax.swing.GroupLayout(Datos);
        Datos.setLayout(DatosLayout);
        DatosLayout.setHorizontalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pestaniaspanle, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DatosLayout.setVerticalGroup(
            DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pestaniaspanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nodo1.add(Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 147, 560, -1));

        RutaSeleccionada.setEditable(false);
        RutaSeleccionada.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        RutaSeleccionada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutaSeleccionadaActionPerformed(evt);
            }
        });
        nodo1.add(RutaSeleccionada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 550, -1));

        fondo.add(nodo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 580, 470));

        NodoPrincipal.setBackground(new java.awt.Color(153, 153, 153));
        NodoPrincipal.setForeground(new java.awt.Color(153, 153, 153));
        NodoPrincipal.setRoundBottomLeft(25);
        NodoPrincipal.setRoundBottomRight(25);
        NodoPrincipal.setRoundTopLeft(25);
        NodoPrincipal.setRoundTopRight(25);
        NodoPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreGestor.setBackground(new java.awt.Color(51, 51, 51));
        NombreGestor.setForeground(new java.awt.Color(153, 153, 153));
        NombreGestor.setRoundBottomLeft(25);
        NombreGestor.setRoundBottomRight(25);
        NombreGestor.setRoundTopLeft(25);
        NombreGestor.setRoundTopRight(25);
        NombreGestor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTOR DE");
        NombreGestor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 170, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Thin", 1, 8)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Version 1.0");
        NombreGestor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 53, -1));

        jLabel10.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ARCHIVOS");
        NombreGestor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 23));

        NodoPrincipal.add(NombreGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 120));

        GraficasAlmacenamiento.setBackground(new java.awt.Color(51, 51, 51));
        GraficasAlmacenamiento.setForeground(new java.awt.Color(153, 153, 153));
        GraficasAlmacenamiento.setRoundBottomLeft(25);
        GraficasAlmacenamiento.setRoundBottomRight(25);
        GraficasAlmacenamiento.setRoundTopLeft(25);
        GraficasAlmacenamiento.setRoundTopRight(25);
        GraficasAlmacenamiento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TotalDeArchivos.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        TotalDeArchivos.setForeground(new java.awt.Color(255, 255, 255));
        TotalDeArchivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalDeArchivos.setText("Numero de Archivos");
        GraficasAlmacenamiento.add(TotalDeArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, -1));

        NumeroArchivos.setEditable(false);
        NumeroArchivos.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        NumeroArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroArchivosActionPerformed(evt);
            }
        });
        GraficasAlmacenamiento.add(NumeroArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, -1));

        EspacioOcupado.setEditable(false);
        EspacioOcupado.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EspacioOcupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioOcupadoActionPerformed(evt);
            }
        });
        GraficasAlmacenamiento.add(EspacioOcupado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, -1));

        EspacioOcupadoLabel.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        EspacioOcupadoLabel.setForeground(new java.awt.Color(255, 255, 255));
        EspacioOcupadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EspacioOcupadoLabel.setText("Espacio Ocupado");
        GraficasAlmacenamiento.add(EspacioOcupadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 130, -1));

        TotalDeDuplicados.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        TotalDeDuplicados.setForeground(new java.awt.Color(255, 255, 255));
        TotalDeDuplicados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalDeDuplicados.setText("Duplicados");
        GraficasAlmacenamiento.add(TotalDeDuplicados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 80, 20));

        EspacioDuplicados.setEditable(false);
        EspacioDuplicados.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EspacioDuplicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspacioDuplicadosActionPerformed(evt);
            }
        });
        GraficasAlmacenamiento.add(EspacioDuplicados, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 40, 20));

        Duplicados.setFont(new java.awt.Font("Roboto Black", 1, 12)); // NOI18N
        Duplicados.setText("Editar Duplicados");
        Duplicados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Duplicados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DuplicadosMouseClicked(evt);
            }
        });
        Duplicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuplicadosActionPerformed(evt);
            }
        });
        GraficasAlmacenamiento.add(Duplicados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 20));

        MusicaLabel.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        MusicaLabel.setForeground(new java.awt.Color(255, 255, 255));
        MusicaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MusicaLabel.setText("Musica");
        GraficasAlmacenamiento.add(MusicaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 90, 20));

        VideosLabel.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        VideosLabel.setForeground(new java.awt.Color(255, 255, 255));
        VideosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VideosLabel.setText("Videos");
        GraficasAlmacenamiento.add(VideosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 90, 20));

        ImagenesLabel.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        ImagenesLabel.setForeground(new java.awt.Color(255, 255, 255));
        ImagenesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImagenesLabel.setText("Imagenes");
        GraficasAlmacenamiento.add(ImagenesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 90, 20));

        NodoPrincipal.add(GraficasAlmacenamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 170, 260));

        ChooseFile.setBackground(new java.awt.Color(204, 204, 204));
        ChooseFile.setForeground(new java.awt.Color(153, 153, 153));
        ChooseFile.setRoundBottomLeft(25);
        ChooseFile.setRoundBottomRight(25);
        ChooseFile.setRoundTopLeft(25);
        ChooseFile.setRoundTopRight(25);
        ChooseFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ChooseFileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ChooseFileMouseExited(evt);
            }
        });
        ChooseFile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Origen9.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        Origen9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Origen9.setText("tus archivos");
        Origen9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Origen9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Origen9MouseClicked(evt);
            }
        });
        ChooseFile.add(Origen9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, 18));

        NodoPrincipal.add(ChooseFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 170, 40));

        fondo.add(NodoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void buscarArchivosRecursiva(File carpeta, List<File> listaArchivos) {
    File[] archivos = carpeta.listFiles(); // jala todos los archivos de la carpeta que selc
    
    if (archivos != null) {
        for (File archivo : archivos) {
            if (archivo.isDirectory()) {
                // Si es una carpeta entra otra vez
                buscarArchivosRecursiva(archivo, listaArchivos);
            } else {
                // si es un archivo lo agrega a la cosa de la lista
                listaArchivos.add(archivo);
            }
        }
    }
}

    private void ChooseFileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileMouseEntered
        ChooseFile.setBackground(Color.black);
        Origen9.setForeground(Color.white);
    }//GEN-LAST:event_ChooseFileMouseEntered

    private void ChooseFileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChooseFileMouseExited
       ChooseFile.setBackground(new Color(204,204,204));
       Origen9.setForeground(Color.black);
    }//GEN-LAST:event_ChooseFileMouseExited

    private void Origen9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Origen9MouseClicked
            JFileChooser FileRuta = new JFileChooser(); // crear la venta del filechooser
            FileRuta.setMultiSelectionEnabled(true);//hacer que seleccione varis archivos
            FileRuta.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES); // Filtro para solo carpetas y archivos
            
            int resultado = FileRuta.showOpenDialog(this); // mostrar ventana para la selección
            if (resultado != JFileChooser.CANCEL_OPTION) { // Si el usuario no cancela la selección
                File carpeta = FileRuta.getSelectedFile(); // Obtener la ruta de carpeta 
                
                if (carpeta == null || carpeta.getName().equals("")) { // ver si si acepta la ruta
                    JOptionPane.showMessageDialog(this, "Error al cargar la carpeta"); // error de carga
                } else {
                        File[] archivos = carpeta.listFiles(); // creo un arreglo de archivos
                        
                        long totalBytes = 0; // para acumular todos loa archivos
                        int cantidadArchivos = 0; // Contador de archivos
                        Map<String, Long> archivosMap = new HashMap<>();//crear el hashmap
                        int archivosDuplicados = 0;
                        
                        for (File archivo : archivos){//para el tipo:file archivo de archivos
                            if (archivo.isFile()){//si es un archivo
                                totalBytes += archivo.length(); //suma el tamano
                                cantidadArchivos++;//suma el archivo 
                                
                                String nombreArchivo = archivo.getName();
                                long tamanoArchivo = archivo.length();
                                if (archivosMap.containsKey(nombreArchivo) && archivosMap.get(nombreArchivo) == tamanoArchivo){//compara nombre y tamano para saber si es duplicado
                                    archivosDuplicados++;//si es duplicado
                                }else{
                                    archivosMap.put(nombreArchivo, tamanoArchivo);
                                }
                            }else if (archivo.isDirectory()){//si es una carpeta
                                File[] subArchivos = archivo.listFiles();//para tener los archivos dentro de carpetas
                                if (subArchivos != null){
                                    for (File subArchivo : subArchivos){
                                        if (subArchivo.isFile());//si es tipo archivo
                                            totalBytes += subArchivo.length();//sumar el tamano
                                            cantidadArchivos++;//contarlo
                                            
                                            // buscar duplicados en niveles bajos 
                                            String nombreSubArchivo = subArchivo.getName();
                                            Long tamanoSubArchivo = subArchivo.length();
                                            
                                            if (archivosMap.containsKey(nombreSubArchivo) && archivosMap.get(nombreSubArchivo) == tamanoSubArchivo){
                                                archivosDuplicados++;
                                            }else{
                                                archivosMap.put(nombreSubArchivo, tamanoSubArchivo);
                                            }
                                            
                                        }
                                    }
                                }
                                
                            }//for que recorre todos los archivos
                        NumeroArchivos.setText(String.valueOf(cantidadArchivos));//llenar el field de ruta
                        double totalGB = totalBytes /(1020.0 * 1020.0 * 1020.0);
                        EspacioOcupado.setText(String.format("%.2f GB",totalGB));
                        EspacioDuplicados.setText(String.valueOf(archivosDuplicados));
                        }//segundo else
            }//else  principal   
            
    }//GEN-LAST:event_Origen9MouseClicked

    private void BotonMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMusicaActionPerformed
        Pestaniaspanle.setSelectedIndex( 0);
    }//GEN-LAST:event_BotonMusicaActionPerformed

    private void BotonMusicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMusicaMouseEntered
         BotonMusica.setBackground(Color.white);
    }//GEN-LAST:event_BotonMusicaMouseEntered

    private void BotonMusicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMusicaMouseExited
         BotonMusica.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_BotonMusicaMouseExited

    private void BotonVideoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVideoMouseEntered
        BotonVideo.setBackground(Color.white);
    }//GEN-LAST:event_BotonVideoMouseEntered

    private void BotonVideoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVideoMouseExited
        BotonVideo.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_BotonVideoMouseExited

    private void BotonVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVideoActionPerformed
                Pestaniaspanle.setSelectedIndex( 1);
    }//GEN-LAST:event_BotonVideoActionPerformed

    private void BotonMusica1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMusica1MouseEntered
        BotonMusica.setBackground(Color.white);
    }//GEN-LAST:event_BotonMusica1MouseEntered

    private void BotonMusica1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMusica1MouseExited
         BotonVideo.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_BotonMusica1MouseExited

    private void BotonMusica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMusica1ActionPerformed

    }//GEN-LAST:event_BotonMusica1ActionPerformed

    private void BotonFlvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFlvMouseEntered
        BotonFlv.setBackground(Color.white);
    }//GEN-LAST:event_BotonFlvMouseEntered

    private void BotonFlvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonFlvMouseExited
         BotonFlv.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_BotonFlvMouseExited

    private void BotonFlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFlvActionPerformed
       Pestaniaspanle.setSelectedIndex( 2);
    }//GEN-LAST:event_BotonFlvActionPerformed

    private void BotonImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonImagenMouseEntered
        BotonImagen.setBackground(Color.white);
    }//GEN-LAST:event_BotonImagenMouseEntered

    private void BotonImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonImagenMouseExited
        BotonImagen.setBackground(new Color(51,51,51));
    }//GEN-LAST:event_BotonImagenMouseExited

    private void BotonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonImagenActionPerformed
        Pestaniaspanle.setSelectedIndex( 3);
    }//GEN-LAST:event_BotonImagenActionPerformed

    private void RutaSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutaSeleccionadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutaSeleccionadaActionPerformed

    private void NumeroArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroArchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroArchivosActionPerformed

    private void EspacioOcupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioOcupadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioOcupadoActionPerformed

    private void EspacioDuplicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspacioDuplicadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspacioDuplicadosActionPerformed

    private void DuplicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuplicadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DuplicadosActionPerformed

    private void DuplicadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DuplicadosMouseClicked
       Pestaniaspanle.setSelectedIndex( 4);
    }//GEN-LAST:event_DuplicadosMouseClicked

        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonFlv;
    private javax.swing.JButton BotonImagen;
    private javax.swing.JButton BotonMusica;
    private javax.swing.JButton BotonMusica1;
    private javax.swing.JButton BotonVideo;
    private com.Gestor.PanelRound Buscar;
    private com.Gestor.PanelRound ChooseFile;
    private com.Gestor.PanelRound Datos;
    private javax.swing.JButton Duplicados;
    private javax.swing.JTextField EspacioDuplicados;
    private javax.swing.JTextField EspacioOcupado;
    private javax.swing.JLabel EspacioOcupadoLabel;
    private com.Gestor.PanelRound Filtrar;
    private com.Gestor.PanelRound GraficasAlmacenamiento;
    private javax.swing.JLabel ImagenesLabel;
    private javax.swing.JLabel MusicaLabel;
    private com.Gestor.PanelRound NodoPrincipal;
    private com.Gestor.PanelRound NombreGestor;
    private javax.swing.JTextField NumeroArchivos;
    private javax.swing.JLabel Origen9;
    private javax.swing.JTabbedPane Pestaniaspanle;
    private javax.swing.JTextField RutaSeleccionada;
    private javax.swing.JLabel TotalDeArchivos;
    private javax.swing.JLabel TotalDeDuplicados;
    private javax.swing.JLabel VideosLabel;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.Gestor.PanelRound nodo1;
    private javax.swing.JPanel panelDuplicados;
    private javax.swing.JPanel panelFlv;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelMusica;
    private javax.swing.JPanel panelVideo;
    private javax.swing.JPanel panelVideo1;
    // End of variables declaration//GEN-END:variables
}
